---

- name: Install Node.js global package {{ item.name if 'name' in item else item }}
  become: true
  become_user: "{{ asdf_user }}"
  npm:
    name: "{{ item.name if 'name' in item else item }}"
    global: true
    version: "{{ item.version if 'version' in item else omit }}"
  environment:
    ASDF_NODEJS_VERSION: "{{ node_version }}"
    PATH: "{{ asdf_shims_dir }}:{{ node_homebrew_dir }}/bin:{{ ansible_env.PATH }}"
  with_items: "{{ node_global_packages }}"
