---

# Homebrew
- name: Install Node.js & npm (Homebrew)
  homebrew: name=node@10 state=present
  become: true
  become_user: "{{ node_homebrew_user }}"
  when: ansible_pkg_mgr == 'homebrew'

# Yum
- name: Install Node.JS & npm (Yum)
  yum:
    name:
      - nodejs
      - npm
    state: present
  when: ansible_pkg_mgr == 'yum'

# Unsupported package managers
- fail: msg="{{ ansible_pkg_mgr }} is not a supported package manager (Homebrew or Yum are supported)"
  when: ansible_pkg_mgr != 'yum' and ansible_pkg_mgr != 'homebrew'
